server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "sifren123"
    sources:
      youtube: true
      soundcloud: true

logging:
  level:
    root: INFO
    lavalink: INFO
